version: "3"
services:
  web:
    stdin_open: true
    restart: on-failure
    build: 
       context: .
       dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_modules 
 #     - .:/app 
      - /DBOX/frontend:/app  
    environment:
      - CHOKIDAR_USEPOLLING=true  
  tests:
    build: 
       context: .
       dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules 
 #     - .:/app 
      - /DBOX/frontend:/app  
    command: ["npm", "run", "test"]  
    environment:
      - CHOKIDAR_USEPOLLING=true            