# Use an existing docker image as a base
FROM node:alpine

# download and install dependency
WORKDIR '/app'

COPY package.json .
RUN npm install
COPY . .


# tell image what to do when it starts as a container
CMD ["npm", "run", "start"]

